server:
  port: 8090
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/marcustrng/graduation-project-ums-configurations.git
          search-paths: configuration
          default-label: main